# Generated by Django 5.0.4 on 2024-05-24 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0003_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='new_price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='min_price',
            field=models.FloatField(null=True),
        ),
    ]
