# Generated by Django 5.0.4 on 2024-05-24 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0005_alter_session_date_date_alter_sub_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session_date',
            name='date',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='sub_category',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
