name: Mirror to GitLab

on:
  push:
    branches:
      - main   # adjust if your default is 'master' or another branch

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Push to GitLab
        env:
          GITLAB_TOKEN: ${{ secrets.GITLAB_BidShopping_TOKEN }}
        run: |
          git remote add gitlab https://oauth2:${GITLAB_BidShopping_TOKEN}@gitlab.com/uhthesis/BidShopping.git
          git push --mirror gitlab
