name: Mirror to GitLab

on:
  push:
    branches:
      - main

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Verify GitLab token
        run: |
          if [ -z "${{ secrets.GITLAB_BidShopping_TOKEN }}" ]; then
            echo "ERROR: GITLAB_BidShopping_TOKEN is not set" && exit 1
          else
            echo "GitLab token is set"
          fi

      - name: Add GitLab remote
        run: |
          # remove any prior remote definition
          git remote remove gitlab 2>/dev/null || true
          git remote add gitlab \
            https://oauth2:${{ secrets.GITLAB_BidShopping_TOKEN }}@gitlab.com/uhthesis/BidShopping.git

      - name: Show git remotes
        run: git remote -v

      - name: Test push permissions (dry-run)
        run: |
          GIT_TRACE=1 git push --mirror gitlab --dry-run

      - name: Mirror push (verbose)
        env:
          GIT_TRACE: 1
        run: git push --mirror gitlab
